name: Cyber Claws V1 Release Notifier

on:
  push:
    tags:
      - "v*"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Message
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\":\"🚀 New Update Released!\n\nVersion: ${{ github.event.release.tag_name }}\nTitle: ${{ github.event.release.name }}\n\n${{ github.event.release.body }}\n\n🎮 Play Game: https://cyber-claws-demo.vercel.app/\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
